### ISSUE TITLE
SeqPurge: -in1 [f1_r1.fastq.gz f2_r1.fastq.gz] and -in2 [f1_r2.fastq.gz f2_r2.fastq.gz] parameters should have the same order

### ISSUE THREAD

**Issue by erskck1** [imgag/ngs-bits#145] opened 2021-05-03 11:20 UTC
If -in1 and -in2 do not have the same order, the program freezes without giving any exception. 

Example : 

SeqPurge  \\
-in1 L1_R1.fastq.gz L2_R1.fastq.gz \\
-in2 L1_R2.fastq.gz L2_R2.fastq.gz                  # this is correct 

Bug occurs when i run the following command : 

SeqPurge \\
-in1 L1_R1.fastq.gz L2_R1.fastq.gz  \\
-in2 **L2_R2.fastq.gz L1_R2.fastq.gz** # this is not correct

If the list of files do not have the same order, this bug occurs.

**Comment by marc-sturm** [comment] 2021-05-03 11:47
Which version of SeqPurge is this?
Does it also occur with the latest version of the master?

**Comment by caspargross** [comment] 2021-05-04 16:34
Error occurs on version `2020_06-9-g409d0101` 
Some of our jobs are currently failing because of this. Reproduce with:

```
/mnt/share/opt/ngs-bits-2020_06-9-g409d0101//SeqPurge         -qc Sample_20021c024_03/analysis_methylseq/data/20021c024_03_stats_fastq.qcML         -in1 Sample_20021c024_03/20021c024_03_S24_L001_R1_001.fastq.gz Sample_20021c024_03/20021c024_03_S24_L002_R1_001.fastq.gz Sample_20021c024_03/20021c024_03_S24_L003_R1_001.fastq.gz Sample_20021c024_03/20021c024_03_S24_L004_R1_001.fastq.gz         -in2 Sample_20021c024_03/20021c024_03_S24_L003_R2_001.fastq.gz Sample_20021c024_03/20021c024_03_S24_L001_R2_001.fastq.gz Sample_20021c024_03/20021c024_03_S24_L002_R2_001.fastq.gz Sample_20021c024_03/20021c024_03_S24_L004_R2_001.fastq.gz         -out1 Sample_20021c024_03/analysis_methylseq/data/20021c024_03_R1.fastq.gz         -out2 Sample_20021c024_03/analysis_methylseq/data/20021c024_03_R2.fastq.gz         -threads 6  > logs/20021c024_03_seqpurge.log 2>&1
 ````
This is mainly a problem of snakemake rearranging the order of input files. But SeqPurge could throw an error if it gets two non-matching read pair files.

**Comment by marc-sturm** [comment] 2021-05-04 19:16
This should be fixed in the current version.
Please test with /mnt/share/opt/ngs-bits-2021_03-51-g693b4519/

**Comment by caspargross** [comment] 2021-05-11 13:33
Thanks, works with the newest version. @erskck1 you can close the issue

**Closed** 2021-06-29 09:21 UTC
Labels: bug
